apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fxxi3ckux-go 
  janus-idp.io/tekton: fxxi3ckux-go
  backstage.io/kubernetes-id: fxxi3ckux-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fxxi3ckux-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml