apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fxxi3ckux-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:0376537e7988a53fcb403fedd9cf9b9258d63766@sha256:ff72f6e84273868a8154112d4fc851cbd8455b9d6ad7baf3d7f43f5999d87539
          name: container-image
